# Generated by Django 3.2.7 on 2021-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('grid_x', models.FloatField(blank=True, null=True)),
                ('grid_y', models.FloatField(blank=True, null=True)),
                ('grid_id', models.CharField(max_length=32)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
