# Generated by Django 3.2.7 on 2021-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210927_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='grid_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='grid_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
